version: "3.7"
services:
  squid:
    image: sameersbn/squid:3.5.27-2
    container_name: squid-proxy
    network_mode: host
    #ports:
    #  - "3128:3128"
    #environment:
    #  - SQUID_USER=${SQUID_USER}
    #  - SQUID_PASS=${SQUID_PASS}
    volumes:
      - ./config:/etc/squid/
      - ./logs:/var/log/squid/
    restart: on-failure
