version: "3.7"
services:
  squid:
    image: sameersbn/squid:3.5.27-2
    container_name: squid-proxy
    build:
      context: .
      dockerfile: Dockerfile-squid
      args:
        - squiduser=${SQUID_USER}
        - squidpass=${SQUID_PASS}
    ports:
      - "3128:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf
      - ./config/hosts:/etc/squid/hosts_template
      - ./logs:/var/log/squid/
    restart: on-failure
    command: sh -c "/usr/bin/startup.sh ${HOST_IP}"
