version: "3.7"
services:
  squid:
    image: sameersbn/squid:3.5.27-2
    container_name: squid-proxy
    build:
      context: .
      dockerfile: Dockerfile-squid
      args:
        - squiduser=${SQUID_USER}
        - squidpass=${SQUID_PASS}
        - hostip=${HOST_IP}
    network_mode: host
    #ports:
    #  - "3128:3128"
    volumes:
      - ./logs:/var/log/squid/
    restart: on-failure
